In [2]:
# Import Python Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df1=pd.read_csv(r"C:\Users\Lenovo\Downloads\E-commerce_Customer_Segmentation_2026.csv")

In [12]:
df1.head()

,customer_id,customer_segment,segment_category,age,age_group,gender,country,city,income_bracket,education_level,...,customer_value_category,activity_status,health_status,churn_risk_category,rfm_category,profitability_category,engagement_level,behavior_segment,device_preference,clv_category
0,CUST-000001,Consumer,High Value Inactive,70,65+,Male,Canada,Winnipeg,150K+,Professional,...,High,Dormant,Excellent,Low,Potential Loyalists,High Profit,Low,Regular Buyer,Multi-Device,High CLV
1,CUST-000002,Premium,High Value Inactive,53,45-54,Female,Germany,Essen,25K-50K,High School,...,Medium,Inactive,Excellent,Medium,At Risk,High Profit,Low,Occasional Buyer,Desktop-First,High CLV
2,CUST-000003,Consumer,High Value Inactive,82,65+,Male,Mexico,Puebla,75K-100K,Bachelors,...,Very High,Dormant,Excellent,Very Low,Champions,High Profit,Low,Regular Buyer,Multi-Device,High CLV
3,CUST-000004,Enterprise,High Value Active,18,18-24,Male,Singapore,Singapore,150K+,Masters,...,Very High,Active,Excellent,Very Low,Champions,High Profit,High,Frequent Buyer,Mobile-First,High CLV
4,CUST-000005,Premium,High Value Active,64,55-64,Male,United Arab Emirates,Fujairah,150K+,PhD,...,Medium,Active,Fair,Medium,Loyal,High Profit,Medium,Occasional Buyer,Desktop-First,High CLV

In [13]:
df1.shape

(50000, 53)

In [8]:
core_cols=[
'customer_id','customer_segment','age','gender','country','income_bracket','tenure_months',
'total_purchases','avg_order_value_usd','total_spent_usd','purchase_frequency',
'days_since_last_purchase','preferred_category_1','shopping_channel','device_used',
'payment_method','return_count','complaint_count','satisfaction_score','loyalty_tier',
'email_open_rate','click_through_rate','conversion_rate','customer_lifetime_value_usd',
'customer_acquisition_cost_usd','customer_profitability_usd','rfm_score','churn_risk_score',
'customer_health_score'
]
df2=df[core_cols].copy()

In [9]:
df2.shape

(50000, 29)

In [10]:
df2.head()

,customer_id,customer_segment,age,gender,country,income_bracket,tenure_months,total_purchases,avg_order_value_usd,total_spent_usd,...,loyalty_tier,email_open_rate,click_through_rate,conversion_rate,customer_lifetime_value_usd,customer_acquisition_cost_usd,customer_profitability_usd,rfm_score,churn_risk_score,customer_health_score
0,CUST-000001,Consumer,70,Male,Canada,150K+,77,28,912.60,25552.80,...,Platinum,0.018,0.067,0.022,21281.07,96.74,21184.33,10,39,100
1,CUST-000002,Premium,53,Female,Germany,25K-50K,80,75,300.86,22564.50,...,Gold,0.084,0.085,0.293,28347.21,199.28,28147.93,8,42,100
2,CUST-000003,Consumer,82,Male,Mexico,75K-100K,86,163,663.91,108217.33,...,Diamond,0.279,0.428,0.222,103909.84,112.39,103797.45,13,0,100
3,CUST-000004,Enterprise,18,Male,Singapore,150K+,26,192,613.60,117811.20,...,Diamond,0.899,0.282,0.142,171318.41,140.71,171177.70,15,14,100
4,CUST-000005,Premium,64,Male,United Arab Emirates,150K+,90,31,651.65,20201.15,...,Gold,0.835,0.094,0.180,24465.47,52.82,24412.65,11,45,60